### ISSUE TITLE
Upgrade after version scheme change?

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#12]
The Ubuntu PPA uses this version numbering:

`3.7.0-alpha1-git-20151018.dfb0f8f-0ppa1~wily2`

This proposed Debian package will use this:

`3.7.0~alpha1+git20151214.cf6498e-1`
`3.7.0~beta-2`

Is there still a way to make users upgrade from the broken PPA's version number?

**Comment by petterreinholdtsen** [comment]
[Hanno Zulla]
> The Ubuntu PPA uses this version numbering:
>
> `3.7.0-alpha1-git-20151018.dfb0f8f-0ppa1~wily2`
>
> This proposed Debian package will use this:
>
> `3.7.0~alpha1+git20151214.cf6498e-1`
> `3.7.0~beta-2`
>
> Is there still a way to make users upgrade from the broken PPA's
> version number?

The sledge to handle these cases is adding an epoc to the version
number, but it is generally consider a thing to avoid if at all
possible.

An alternative might be to adjust the dependency of sonic-pi to pull in
the old version, or rename the library.

A better alternative is perhaps to wait until upstream releases 3.7.1,
which would solve the issue without much fuzz.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by hzulla** [comment]
Yes, but upstream is very slow with their releases...
