### ISSUE TITLE
Packaging question: missing Priority

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#2]
During build, this warning is shown:

```
dpkg-genchanges: warning: missing Priority for source files
dpkg-genchanges: warning: missing Priority for binary package supercollider-sc3-plugins; using '-'
dpkg-genchanges: not including original source code in upload
```

Ok, which priority should be used and where?

**Comment by petterreinholdtsen** [comment]
I my memory is correct, priority should be optional.  See <URL: https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control >

**Comment by petterreinholdtsen** [comment]
https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control

**Comment by danstowell** [comment]
petter is correct

**Comment by hzulla** [comment]
Thanks.
