### ISSUE TITLE
Packaging question: How to handle nova-simd?

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#3]
[Upstream](https://github.com/supercollider/sc3-plugins) expects users to get [current version of nova-simd from github](https://github.com/timblechmann/nova-simd) prior to building.

Debian's supercollider source package version supercollider-3.6.6~repack-2 repacks the source tarball to include nova-simd.

Here, I added nova-simd as part of `debian/patches/01-nova-simd.patch` instead.

What is the preferred Debian solution?

(Is it worth investigating to package nova-simd for Debian, instead?)

**Comment by petterreinholdtsen** [comment]
Sound like a topic to discuss with the Debian maintainer of supercollider.  I have no idea.

**Comment by danstowell** [comment]
The very best debian way is as follows: (1) the package "supercollider-dev" should include the nova-simd headers; (2) your plugins package should depend on "supercollider-dev".

Problem is, step 1 is not the case!

We can propose step 1 to the debian multimedia team. That is not an immediate solution for you. (Presumably our proposal would be to put the nova-simd headers into /usr/include/SuperCollider ? I've not tested that.) Thoughts?

**Comment by hzulla** [comment]
I asked on #debian-multimedia IRC before your response. One maintainer there said it would be OK to package nova-simd as a separate package that both supercollider and supercollider-sc3-plugins build-depend on.

But it's your call. Please let me know how to proceed.

**Comment by danstowell** [comment]
That sounds like a good approach, yes

**Comment by hzulla** [comment]
@danstowell I asked @timblechmann and he'd rather want packagers to include the full nova-simd source in each source package. See https://github.com/timblechmann/nova-simd/issues/5

**Comment by hzulla** [comment]
So we're sticking with the debian/patch for the time being, unless the Debian Multimedia maintainers complain about it.
