### ISSUE TITLE
Packaging question: How to handle libstk?

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#4]
[Upstream](https://github.com/supercollider/sc3-plugins) contains two different STK plugins, the older StkUGens and the more recent StkInst.

Both require the [STK library](https://github.com/thestk/stk/) to build.

StkUGens comes with a [convenience copy of STK version 4.4.4](https://github.com/supercollider/sc3-plugins/tree/a193b437dad5f3343184572ecc8d30970e5011e8/source/StkUGens).

StkInst expects users to [fetch the most recent version 4.5.0 from github](https://github.com/supercollider/sc3-plugins/blob/95327f82cf9034dd7f0f33bcf95fffc3b6ec173c/source/StkInst/CMakeLists.txt#L9) and then build it.

Both StkUGens and StkInst build fine with the Debian-supplied shared libstk library package. `debian/patches/02-debian-libstk.patch` patches the upstream source to use the Debian package and ignore the convenience copies.

Is this correct?

What to do with the convenience copy in the upstream tarball? Does it have to be removed for the Debian source tarball or is it ok to just ignore it during build?

**Comment by danstowell** [comment]
The convenience copy has to be removed please. See here for an [example of how we exclude stuff from the main sc source](http://anonscm.debian.org/cgit/pkg-multimedia/supercollider.git/tree/debian/rules#n45).

Your patch looks good. It makes me think though, maybe it would be good to propose to the main sc3-plugins upstream, that there should be a cmake flag something like USE_SYSTEM_STK.

**Comment by danstowell** [comment]
Hi all - I [proposed a new build flag SYSTEM_STK](https://github.com/supercollider/sc3-plugins/pull/53) - please could you test & review the pull request?
