### ISSUE TITLE
Packaging question: Where to put ladspalist?

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#5]
The plugins come with an optional binary:

[`source/LadspaUGen/sc/README`](https://github.com/deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins/blob/50e065847d0209dfbc9f3ce9eb0eb68c35795ceb/source/LadspaUGen/sc/README)
> This UGen lets you run any LADSPA plugin inside SuperCollider.
> [..]
> Optionally, copy the included 'ladspalist' utility to somewhere in your PATH
> [..]
> Run the included 'ladspalist' in a shell to find the info about the plugin you want

Where should the `ladspalist` binary be put? For now, it's in `/usr/bin`.

**Comment by danstowell** [comment]
Yes, it should go in /usr/bin

**Comment by petterreinholdtsen** [comment]
[Hanno Zulla]
> Where should the `ladspalist` binary be put? For now, it's in
> `/usr/bin`.

Is this binray specific to supercollider-sc3-plugins?  There are several
ladspa related packages, and it might be confusing if that name only
give information related to one of the packages using ldaspa.

I would suggest to put it in /usr/lib/supercollider-sc3-plugins/ until
it is clear how the binary will be used.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by danstowell** [comment]
@petterreinholdtsen maybe. But there are no other packages providing "ladspalist" as far as I'm aware, and the binary is not actually very SC specific. It does not require any SC headers or libs, it simply lists to stdout the available ladspa plugins. I'd suggest it's fine for the main path.

**Comment by hzulla** [comment]
Thanks.

**Comment by hzulla** [comment]
@danstowell - is ladspalist required for packaging? The Debian Multimedia team [seems to think it isn't needed](http://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2015-December/048928.html) as there are alternative commands doing the same thing. I wouldn't mind to just leave it out and not distribute it. What do you think?

**Comment by danstowell** [comment]
I don't know

**Comment by hzulla** [comment]
Thanks! I'll check the other command and will see if we really need ladspalist. To me, it appears to be entirely optional.
