### ISSUE TITLE
Lintian: arch-dep-package-has-big-usr-share

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#6]
The content of /usr/share is not arch-dependent and should be split up into a separate package.

See https://lintian.debian.org/tags/arch-dep-package-has-big-usr-share.html

**Comment by hzulla** [comment]
What should be the name of that package? supercollider-sc3-plugins-common?

**Comment by petterreinholdtsen** [comment]
I am not sure.  Looking at the files, most of them seem to be documentation.  Perhaps supercollider-sc3-plugins-doc make more sense?

**Comment by hzulla** [comment]
@danstowell could you please clarify the meaning of these files, what is `/source/DEINDUGens/sc/Greyhole.sc` - is it documentation, is it source compiled at runtime? Where should we put it in a package? On the system, it is installed to `/usr/share/SuperCollider/Extensions/SC3plugins/DEINDUGens/Greyhole.sc`. Thanks!

**Comment by danstowell** [comment]
I haven't got a flaming clue what that file is.
Remember that sc3-plugins is a community repository, and we deliberately do not exert as strong policing of it as in the main SC codebase.

If you see a `.sc` file it's probably a SuperCollider class file. Those are not documentation. However they are architecture-independent. So the best thing to do would be split them off into `supercollider-sc3-plugins-common`. For inspiration, have a look at `supercollider-common` which is the arch-independent main SC stuff.

**Comment by hzulla** [comment]
Great, thank you!

**Comment by hzulla** [comment]
So supercollider-sc3-plugins-common it shall be. :-)

**Comment by hzulla** [comment]
@danstowell can you tell me if these .sc files are needed at runtime? It's a fairly large chunk of data, so is it required to be installed for end users of the sc3 plugins? (Forgive my ignorance of the inner workings of supercollider.)

**Comment by hzulla** [comment]
(We have a motivation to keep the package small, as Raspbian is one of the install targets.)

**Comment by danstowell** [comment]
Yes they are 100% required. It's weird that you are packaging sc3-plugins without knowing this! Will you be doing any testing with SC users as opposed to SPi users? I realise now that you might end up packaging it without noticing if for some reason it doesn't work for the primary platform (SC).

**Comment by petterreinholdtsen** [comment]
[danstowell]
> Yes they are 100% required. It's weird that you are packaging
> sc3-plugins without knowing this! Will you be doing any testing with
> SC users as opposed to SPi users? I realise now that you might end up
> packaging it without noticing if for some reason it doesn't work for
> the primary platform (SC).

The way we test is by using sonic-pi, which uses supercollider to create
sound (in other word, it is a SC user).  If sonic-pi can play the sound,
we assume the plugins and supercollider is working.

Is there a way to create a testsuite test in debian/tests/ that can
verify more directly that the plugins are working?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by danstowell** [comment]
OK.

I've not tried to do debian tests. But in case it helps, there are a couple of Quarks that provide unit tests for items in sc3-plugins: "McldUnitTests" and "MachineListeningUnitTests"

**Comment by danstowell** [comment]
No, wait, "sonic-pi uses supercollider" is an ambiguous statement. I know for sure that sonic-pi uses scsynth to create sound, but if it doesn't use sclang then the statement misses the point. Does sonic-pi use sclang (e.g. to create synthdefs)?

**Comment by hzulla** [comment]
Hi @danstowell,

it's true that I'm not a supercollider user and the packaging of sc3 plugins is done as a dependency for sonic-pi. We test the plugins by using Sonic Pi and we try our best to follow the guidelines of packaging by fixing as many bugs and warnings we can, even if they don't affect Sonic Pi. As a result, you can see that we already fixed some minor Linux issues for sc3 plugins.

I would welcome if a "true" SuperCollider user would join us or help us testing. Do you have an idea where we can recruit one?

Regarding your feedback, Sonic Pi only uses scsynth. It does ship with synthdefs at https://github.com/samaaron/sonic-pi/tree/master/etc/synthdefs, but if I understand that correctly, compiles them prior to shipping. (Correct?)

All in all, I'm really excited about this and hope to be as useful as possible for the SuperCollider project by packaging this correctly and ready for use by non-Sonic-Pi users.

**Comment by danstowell** [comment]
Yes it seems that Sonic Pi doesn't use sclang, so testing the package using SPi doesn't demonstrate that (for example) the .sc files are correctly installed for a sclang user.

I'm not currently a SuperCollider developer - I was in the past, but I've now taken a back-seat position. You'd find testers on the sc mailing lists. I'm giving advice because I'm one of the main people keeping an eye on the debian packaging! That's why I'm able to give feedback but I have no time myself for properly joining the effort. I'm really glad to see the motivated work you're putting in.

**Comment by hzulla** [comment]
And your advice is incredibly helpful, so thanks a lot!

Right now, Sonic Pi is shipping [pre-compiled binary versions of the sc3 plugins on Raspbian](https://github.com/samaaron/sonic-pi/tree/master/app/server/native/raspberry) - this is something we definitely want to improve on.

So if I understand this correctly, Sonic Pi uses scsynth which doesn't need the source files of the sc3 plugins in order to use them, but once the user runs sclang, the sc3 plugin source files are needed. Correct?

**Comment by hzulla** [comment]
What I'm trying to confirm is: Will Sonic Pi run fine without the `.sc` files, only using `scsynth` and the compiled `.so` files of the sc3 plugins?

Because if that is the case, we could reduce the storage footprint of the Sonic Pi dependencies by splitting things up sc3 plugins into two packages, `supercollider-sc3-plugins` and `supercollider-sc3-plugins-common`, and making the second recommended but not required by the first. Then `sclang` users can install it when needed, but Sonic Pi users don't have to.

@samaaron, could you help us here and clear things up, please?

**Comment by danstowell** [comment]
"source files" is not the right word really, to me that means the .cpp files. If you replace that with "class files", then you're correct.

In response to your second comment just now - if you have a package named `*-common` then it should be common! It might be better to have this layout:
* `supercollider-sc3-plugins` - a meta-package that depends on the three packages below
* `supercollider-sc3-plugins-scsynth` - the .so files (and anything else needed by the server)
* `supercollider-sc3-plugins-sclang` - the .sc files, .scdoc files, etc
* `supercollider-sc3-plugins-common` - common architecture-independent files

Then, SPi would depend only on the two -common and -scsynth packages (and therefore wouldn't drag in any sclang stuff it didn't need), while a "normal" SC user would install the metapackage.

**Comment by hzulla** [comment]
Sounds good. I'll try to identify the files for each category, but will need your help reviewing my choices later, please.

**Comment by hzulla** [comment]
@danstowell I looked at the file list. Please correct me if I'm wrong here:

`supercollider-sc3-plugins-scsynth`
* `/usr/bin/ladspalist`
* `/usr/lib/SuperCollider/plugins/*.so`

`supercollider-sc3-plugins-sclang`
* `/usr/share/SuperCollider/Extensions/SC3plugins/*`

There is no need for `supercollider-sc3-plugins-common`.

**Comment by hzulla** [comment]
Ok, I have split up the packages like that in the current version and it seems to work ok.

**Comment by danstowell** [comment]
@hzulla yes this looks good to me.

**Comment by hzulla** [comment]
Thanks! I will close this for now and will try to recruit testers from the SuperCollider users mailing list once the other packaging bugs are fixes.
