### ISSUE TITLE
Add debian/watch rule, remove libstk

### ISSUE THREAD

**Issue by hzulla** [deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins#7]
Debian Multimedia maintainers asked us to add a debian/watch rule and Files-Excluded rule to remove the embedded copy of libstk.

**Comment by hzulla** [comment]
On IRC, this was mentioned as a good example:

https://sources.debian.net/src/soundconverter/3.0.0~alpha1%2Bgit20151119-1/debian/rules/#L15

**Comment by petterreinholdtsen** [comment]
This is a slight misunderstanding.  The request was to either document libstk presence in debian/copyright or remove it from the tarball using Files-Excluded + uscan.  I recommend keeping the tarball identical to upstream until we have to repack, and document the copyrights instead.

I added a debian/watch file anyway, to allow the infrastructure to discover new versions when they show up.
